export const SPACE_VISUAL_TOKENS = Object.freeze({
  colors: Object.freeze({
    brandTeal: "#67c2be",
    ink: "#17282a",
    paper: "#f3f0e7",
    atmosphere: "#a9bfbc",
    architecture: "#c7d0cc",
    wall: "#9eaeaa",
    floor: "#3f4d4d",
    ceiling: "#e8e4d8",
    metal: "#667271",
    signal: "#ef8b61",
    inkOutline: "#17282a",
  }),
  toonBands: Object.freeze({
    shadow: "#31413f",
    mid: "#69827e",
    light: "#b9cbc6",
    highlight: "#f3f0e7",
  }),
  fog: Object.freeze({ density: 0.008, near: 12, far: 42 }),
  lighting: Object.freeze({
    ambientIntensity: 0.28,
    hemisphere: Object.freeze({ sky: "#dce9e4", ground: "#3f4d4d", intensity: 0.55 }),
    key: Object.freeze({ position: [-5, 10, 4] as const, color: "#f3f0e7", intensity: 1 }),
    fill: Object.freeze({ position: [5, 3, -7] as const, color: "#67c2be", intensity: 0.22 }),
  }),
  hud: Object.freeze({
    topPx: 8,
    heightPx: 36,
    panelMaxWidthPx: 360,
    panelPaddingPx: 12,
    rowGapPx: 10,
    controlMinHeightPx: 32,
    settingsSizePx: 32,
    fontSizePx: 13,
    panelFontSizePx: 12,
    fontWeight: 650,
    letterSpacingEm: 0.08,
    focusOutlinePx: 3,
    focusOffsetPx: 3,
  }),
});

export const SPACE_VISUAL_CSS_PROPERTIES = Object.freeze({
  "--space-brand-teal": SPACE_VISUAL_TOKENS.colors.brandTeal,
  "--space-ink": SPACE_VISUAL_TOKENS.colors.ink,
  "--space-paper": SPACE_VISUAL_TOKENS.colors.paper,
  "--space-atmosphere": SPACE_VISUAL_TOKENS.colors.atmosphere,
  "--space-architecture": SPACE_VISUAL_TOKENS.colors.architecture,
  "--space-wall": SPACE_VISUAL_TOKENS.colors.wall,
  "--space-floor": SPACE_VISUAL_TOKENS.colors.floor,
  "--space-ceiling": SPACE_VISUAL_TOKENS.colors.ceiling,
  "--space-metal": SPACE_VISUAL_TOKENS.colors.metal,
  "--space-signal": SPACE_VISUAL_TOKENS.colors.signal,
  "--space-hud-surface": "rgb(23 40 42 / 0.78)",
  "--space-hud-panel": "rgb(23 40 42 / 0.94)",
  "--space-hud-border": "rgb(243 240 231 / 0.28)",
  "--space-hud-panel-border": "rgb(243 240 231 / 0.22)",
  "--space-hud-selected": "rgb(103 194 190 / 0.28)",
}) satisfies Readonly<Record<`--${string}`, string>>;
